version: "3.0"

  x-app-service: &default-app
    build: .
    command: ''
    environment:
      - shared.log.mongo.host=mongodb
      - shared.log.mongo.port=27017
    depends_on:
      - mongodb
      - kibana
      - elasticsearch
    volumes:
      - .:/code:delegated
      - node_modules:/code/node_modules:delegated

services:

  elasticsearch:
    container_name: siem-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - "9200:9200"

  kibana:
    container_name: siem-kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://siem-elastic:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    networks:
      - es-net
    ports:
      - "27017:27017"

  app:
    <<: *default-app

  logbunker-backoffice:
    <<: *default-app
    command: bash -c "make run/backoffice"
    ports:
      - "3001:3000"
    networks:
      - es-net

  logbunker-bunker:
    <<: *default-app
    command: bash -c "make run/bunker"
    ports:
      - "8000:8000"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge